language: python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -u root -e "create database p3"
  - mysql -u root p3 < test/travis.sql
install:
  - pip install pytest
  - pip install mysqlclient
  - pip install seaborn
  - pip install pandas
script:
  - pytest test/tests.py
